[workspace]
resolver = "2"
members = [
    "crates/openconnect-sys",
    "crates/openconnect-core",
    "crates/openconnect-gui/src-tauri",
]

[workspace.dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.11.25", features = ["multipart"] }
tokio = { version = "1.36.0", features = ["full"] }