on:
  workflow_dispatch:
  push:
    paths:
      - "crates/openconnect-sys"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64 }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
          base-devel
          mingw-w64-x86_64-toolchain
          automake
          libtool
          gettext
          autotools
          pkg-config
          openssl
          openssl-devel
          mingw-w64-x86_64-openssl
          libxml2
          libxml2-devel
          mingw-w64-x86_64-libxml2
          libiconv
          libiconv-devel
          mingw-w64-x86_64-libiconv
          zlib
          zlib-devel
          mingw-w64-x86_64-zlib
          liblz4
          liblz4-devel
          mingw-w64-x86_64-lz4
          liblzma
          liblzma-devel
          mingw-w64-x86_64-xz
          icu
          icu-devel
          mingw-w64-x86_64-icu
        pacboy: >-
          toolchain:p

    - name: '🚧 Build TOOL'
      run: |
        echo "Testing"
        ls /mingw64/lib/libxml2.a
